version: '3.8'

services:
  backend:
    build: ./backend/src/JobAgentAi.Api
    container_name: JobAgentAi-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build: ./frontend/JobAgentAi-web
    container_name: JobAgentAi-web
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  pyservice:
    build: ./pyservice/src
    container_name: book-analysis-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: JobAgentAi-network
